// Enhanced Export Functions with Real Data and Structure Formats

// Enhanced Schema Download with Real Structure
function downloadSchema() {
    if (currentGeneratedSchema) {
        const enhancedSchema = generateEnhancedSchema(currentGeneratedSchema);
        downloadFile('database-schema.sql', enhancedSchema);
        showToast('📄 Enhanced SQL schema downloaded with real structure!', 'success');
    } else {
        const demoSchema = generateProductionReadySchema();
        downloadFile('database-schema.sql', demoSchema);
        showToast('📄 Production-ready schema downloaded!', 'success');
    }
}

// Enhanced API Download with Real Endpoints
function downloadAPICode() {
    if (currentGeneratedAPI) {
        const enhancedAPI = generateEnhancedAPI(currentGeneratedAPI);
        downloadFile('api-server.js', enhancedAPI);
        showToast('🚀 Enhanced API with real endpoints downloaded!', 'success');
    } else {
        const demoAPI = generateProductionReadyAPI();
        downloadFile('api-server.js', demoAPI);
        showToast('🚀 Production-ready API downloaded!', 'success');
    }
}

// Enhanced ERD Download with Real Structure
function downloadERDDiagram() {
    try {
        const schema = currentGeneratedSchema || generateDemoSchema();
        const analysis = parseSchemaToAnalysis(schema);
        const erdSvg = generateEnhancedERDSVG(analysis);
        
        const blob = new Blob([erdSvg], { type: 'image/svg+xml' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `erd-diagram-${currentSessionId}-${Date.now()}.svg`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        
        showToast('📊 Enhanced ERD diagram with real data structure downloaded!', 'success');
    } catch (error) {
        console.error('ERD download error:', error);
        showToast('❌ ERD download failed', 'error');
    }
}

// New Markdown Documentation Download
function downloadMarkdownDocs() {
    try {
        const schema = currentGeneratedSchema || generateDemoSchema();
        const api = currentGeneratedAPI || generateDemoAPICode();
        const docs = generateMarkdownDocumentation(schema, api);
        
        downloadFile(`database-api-docs-${currentSessionId}.md`, docs);
        showToast('📄 Complete markdown documentation downloaded!', 'success');
    } catch (error) {
        console.error('Docs download error:', error);
        showToast('❌ Documentation download failed', 'error');
    }
}

// Export All Formats Function
function exportAllFormats() {
    try {
        const schema = currentGeneratedSchema || generateProductionReadySchema();
        const api = currentGeneratedAPI || generateProductionReadyAPI();
        const analysis = parseSchemaToAnalysis(schema);
        const erdSvg = generateEnhancedERDSVG(analysis);
        const docs = generateMarkdownDocumentation(schema, api);
        
        // Download all formats
        downloadFile(`schema-${currentSessionId}.sql`, generateEnhancedSchema(schema));
        downloadFile(`api-${currentSessionId}.js`, generateEnhancedAPI(api));
        downloadFile(`docs-${currentSessionId}.md`, docs);
        
        const blob = new Blob([erdSvg], { type: 'image/svg+xml' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `erd-${currentSessionId}.svg`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        
        showToast('📦 All formats exported successfully!', 'success');
    } catch (error) {
        console.error('Export all error:', error);
        showToast('❌ Export failed', 'error');
    }
}

// Generate Enhanced Schema with Real Data
function generateEnhancedSchema(baseSchema) {
    const timestamp = new Date().toISOString();
    const sessionInfo = `-- Generated by AI Database-to-API Agent
-- Session: ${currentSessionId}
-- Generated: ${timestamp}
-- Real data structure with constraints and indexes

`;
    
    let enhanced = sessionInfo + baseSchema;
    
    // Add indexes for performance
    enhanced += "\n\n-- Performance Indexes\n";
    const tables = parseSchemaToTables(baseSchema);
    tables.forEach(table => {
        table.columns.forEach(col => {
            if (col.name.includes('_id') && !col.constraints?.includes('PRIMARY KEY')) {
                enhanced += `CREATE INDEX idx_${table.name}_${col.name} ON ${table.name}(${col.name});\n`;
            }
            if (col.name === 'email' || col.name === 'username') {
                enhanced += `CREATE INDEX idx_${table.name}_${col.name} ON ${table.name}(${col.name});\n`;
            }
        });
    });
    
    // Add sample data
    enhanced += "\n\n-- Sample Data for Testing\n";
    tables.forEach(table => {
        enhanced += generateSampleData(table);
    });
    
    return enhanced;
}

// Generate Sample Data for Tables
function generateSampleData(table) {
    let data = `\n-- Sample data for ${table.name}\n`;
    
    if (table.name === 'users' || table.name === 'customers') {
        data += `INSERT INTO ${table.name} (name, email) VALUES\n`;
        data += `  ('John Doe', 'john@example.com'),\n`;
        data += `  ('Jane Smith', 'jane@example.com'),\n`;
        data += `  ('Bob Johnson', 'bob@example.com');\n`;
    } else if (table.name === 'products') {
        data += `INSERT INTO ${table.name} (name, price, description) VALUES\n`;
        data += `  ('Laptop', 999.99, 'High-performance laptop'),\n`;
        data += `  ('Mouse', 29.99, 'Wireless optical mouse'),\n`;
        data += `  ('Keyboard', 79.99, 'Mechanical keyboard');\n`;
    } else if (table.name === 'orders') {
        data += `INSERT INTO ${table.name} (customer_id, total_amount, status) VALUES\n`;
        data += `  (1, 1109.97, 'completed'),\n`;
        data += `  (2, 29.99, 'pending'),\n`;
        data += `  (3, 79.99, 'shipped');\n`;
    } else {
        data += `-- INSERT INTO ${table.name} (column1, column2) VALUES ('value1', 'value2');\n`;
    }
    
    return data;
}